function txt = mx_preamble()
% mx_preamble — the mx/mex declaration block prepended to a MEX source
% for the matlabcc track.  The corpus files `#include "mex.h"`, which
% cc_int skips (preprocessor lines), so the types/constants/macros the
% source relies on are provided here directly instead (typedefs + enums;
% no function prototypes needed — every mx/mex call becomes a shim and
% cc_int's libargt/libret tables drive promotions and return types).
txt = [
    'typedef int mxArray;' 10 ...
    'typedef int MATFile;' 10 ...
    'typedef long mwSize;' 10 ...     % 8 bytes: the mx layout (and the real
    'typedef long mwIndex;' 10 ...    % API) index ir/jc with size_t words
    % 8 bytes, not MathWorks' 2: this track's storage model gives char and
    % logical data ONE ELEMENT PER 8-BYTE SLOT (x86sim.m sim_mx_alloc forces
    % es = 8 for classes 3 and 4, and mxCreateString stores them with
    % sim_storeN(..., 8)).  The compiled element width has to be the slot
    % width - declared int (4) it walked half a slot per element and read
    % code, padding, code: mxchar.c's get op answered [97 0 98] for 'abc'
    % where gcc's packed read answers [97 98 99].
    'typedef long mxChar;' 10 ...
    'typedef long mxLogical;' 10 ...
    'typedef unsigned int mxComplexity;' 10 ...
    'typedef char int8_t;' 10 ...
    'typedef char uint8_t;' 10 ...
    'typedef short int16_t;' 10 ...
    'typedef short uint16_t;' 10 ...
    'typedef word int32_t;' 10 ...
    'typedef word uint32_t;' 10 ...
    'typedef long int64_t;' 10 ...
    'typedef unsigned uint64_t;' 10 ...
    'enum { mxREAL = 0, mxCOMPLEX = 1 };' 10 ...
    'enum { NULL = 0 };' 10 ...
    'typedef enum { mxUNKNOWN_CLASS = 0, mxCELL_CLASS = 1, mxSTRUCT_CLASS = 2,' 10 ...
    '       mxLOGICAL_CLASS = 3, mxCHAR_CLASS = 4, mxFUNCTION_CLASS = 5,' 10 ...
    '       mxDOUBLE_CLASS = 6, mxSINGLE_CLASS = 7,' 10 ...
    '       mxINT8_CLASS = 8, mxUINT8_CLASS = 9,' 10 ...
    '       mxINT16_CLASS = 10, mxUINT16_CLASS = 11,' 10 ...
    '       mxINT32_CLASS = 12, mxUINT32_CLASS = 13,' 10 ...
    '       mxINT64_CLASS = 14, mxUINT64_CLASS = 15,' 10 ...
    '       mxOBJECT_CLASS = 17 } mxClassID;' 10 ...
    'enum { mxNULL = -1 };' 10 ...
    ];
end

